version: "3.8"

services:
  fastping_app:
    build: .
    container_name: fastping_app
    ports:
      - "9876:9876"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: fastping_redis
    restart: unless-stopped
    
version: "3.8"

services:
  fastping_app:
    build: .
    container_name: fastping_app
    ports:
      - "9876:9876"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: fastping_postgres
    environment:
      POSTGRES_USER=fastping
      POSTGRES_PASSWORD=changeme
      POSTGRES_DB=fastpingdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fastping_redis
    restart: unless-stopped

volumes:
  pgdata:
